from __future__ import annotations
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEXT_SUFFIXES = {'.cs','.csproj','.sln','.ps1','.py','.md','.txt','.patch','.json','.yml','.yaml','.gitignore','.gitattributes'}
FORBIDDEN_NAMES = {
    'rlyehshoujotaix_cl.exe','GameAssembly.dll','UnityPlayer.dll','global-metadata.dat',
    'Assembly-CSharp.dll','Unity.TextMeshPro.dll','UnityEngine.TextMeshPro.dll',
    '_AutoGeneratedTranslations.txt','AutoTranslatorConfig.ini','dev.rlyehshoujotai.textfix.cfg',
    'zz_Rlyeh_UIFix.txt','zz_Rlyeh_GachaFix.txt','notoserifkr_sdf'
}

ALLOWED_GAME_TITLE = '邪神戦記ルルイエ少女隊'
JAPANESE_OR_CJK = re.compile(r'[\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff]')

PATTERNS = {
    'windows_user_path': re.compile(r'(?i)[A-Z]:\\Users\\[^\\\r\n]+\\'),
    'unix_home_path': re.compile(r'/(?:home|Users)/[^/\s]+/'),
    'container_path': re.compile(r'/(?:mnt/data|home/oai)/'),
    'likely_secret': re.compile(r'(?i)(?:api[_ -]?key|token|password)\s*[=:]\s*["\']?[A-Za-z0-9_\-]{12,}')
}

def fail(msg: str) -> None:
    print(f'FAIL: {msg}')
    failures.append(msg)

failures: list[str] = []
for p in ROOT.rglob('*'):
    if not p.is_file() or '.git' in p.parts:
        continue
    if p.name in FORBIDDEN_NAMES:
        fail(f'forbidden file name: {p.relative_to(ROOT)}')
    if p.suffix.lower() in {'.dll','.exe'}:
        fail(f'binary should not be committed in source repo: {p.relative_to(ROOT)}')
    if p.suffix.lower() not in TEXT_SUFFIXES and p.name not in {'.gitignore','.gitattributes','LICENSE'}:
        continue
    try:
        text = p.read_text(encoding='utf-8')
    except UnicodeDecodeError:
        continue
    for name, pattern in PATTERNS.items():
        if pattern.search(text):
            fail(f'{name}: {p.relative_to(ROOT)}')
    # No game dialogue/translation dataset should be present. The exact official game
    # title is allowed once as project identification; other Japanese/CJK text is rejected.
    content_for_language_scan = text.replace(ALLOWED_GAME_TITLE, '')
    if JAPANESE_OR_CJK.search(content_for_language_scan):
        fail(f'japanese_or_cjk_text: {p.relative_to(ROOT)}')

if failures:
    print(f'\n{len(failures)} issue(s) found.')
    sys.exit(1)
print('PASS: public-repository safety audit completed with no findings.')
